# Generated by Django 4.1.2 on 2022-10-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="usename",
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
